name: Example CI
on: ["push", "pull_request"]

jobs:
  test:
    name: Check if examples compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - run: cd examples/controller-runtime && go build -o /tmp/test main.go
